### ISSUE TITLE
Docker compose files on deploy does not have restart property

### ISSUE THREAD

**Issue by dejanstrancar** [MightyMoud/sidekick#62]
When using Sidekick v.0.6.6 installed with brew generated docker-compose.yml file does include restart property. (`restart: unless-stopped`).

When doing it on same app from the github code source, it does include it.

But when `deploy` is done that property is removed.

Recreation:

Dockerfile
```
FROM node:20
WORKDIR /app
EXPOSE 3000
```

Brew v.0.6.6 version:
`sidekick launch`

Generated `docker-compose.yml`:
```
services:
    testing:
        image: testing
        labels:
            - traefik.enable=true
            - traefik.http.routers.testing.rule=Host(`testing.167.99.243.82.sslip.io`)
            - traefik.http.services.testing.loadbalancer.server.port=3000
            - traefik.http.routers.testing.tls=true
            - traefik.http.routers.testing.tls.certresolver=default
            - traefik.docker.network=sidekick
        networks:
            - sidekick
networks:
    sidekick:
        external: true
```

Github source running from source:

`sidekick launch`

Generated `docker-compose.yml`:
```
services:
    testing:
        image: testing
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.testing.rule=Host(`testing.167.99.243.82.sslip.io`)
            - traefik.http.services.testing.loadbalancer.server.port=3000
            - traefik.http.routers.testing.tls=true
            - traefik.http.routers.testing.tls.certresolver=default
            - traefik.docker.network=sidekick
        networks:
            - sidekick
networks:
    sidekick:
        external: true
```
